name: MobTweaks
main: com.octagami.mobtweaks.MobTweaks
version: 0.0.4
author: octagami
website: http://github.com/octagami
description: >
    Tweaks things related to mobs
softdepend: []
commands:
  mobtweaks:
    description: General plugin command
    permission: mobtweaks.admin
    usage: /<command> [help|reload]
permissions:
  mobtweaks.admin:
      description: Reloads the config
      default: op